### ISSUE TITLE
run error

### ISSUE THREAD

**Issue by wpp201820601009** [LucyWang01/SURF_Safe_Reconfiguration#1]
Hello, I want to ask for some questions about running highway_exit.py. At the beginning of the run, the Autonomous mode not available: Speed limit requirement not satisfied will appear on the pygame interface. The car is stationary, and if the automatic mode is forced to be used, there will be a running error. What should I do?

**Comment by KeyingLucyWang** [comment]
Hi, for the highway_exit example, you would have to enter the highway manually (by pressing the arrow keys or WASD). Once the vehicle is on the highway, the speed limit would be updated to 90kmh and you will be prompted to switch into the autonomous mode.

**Comment by wpp201820601009** [comment]
Thank you very much for your reply. When I try to use the direction keys or WASD to manually control the vehicle, once the car turns a corner, the following errors will appear

Traceback (most recent call last):
  File "/home/wpp/Downloads/SURF_Safe_Reconfiguration-master/highway_exit.py", line 1264, in <module>
    main()
  File "/home/wpp/Downloads/SURF_Safe_Reconfiguration-master/highway_exit.py", line 1256, in main
    game_loop(args)
  File "/home/wpp/Downloads/SURF_Safe_Reconfiguration-master/highway_exit.py", line 1074, in game_loop
    controller._conditions_satisfied, additional_info = check_AD_conditions(world)
  File "/home/wpp/Downloads/SURF_Safe_Reconfiguration-master/highway_exit.py", line 978, in check_AD_conditions
    if (weather_params.cloudyness > cloudiness_threshold
AttributeError: 'WeatherParameters' object has no attribute 'cloudyness'

The first time I contacted Carla, I didn't know much about many aspects. Thank you again for your patience

**Comment by KeyingLucyWang** [comment]
That's strange. Which version of Carla are you using? I used Carla.0.9.6 and some of the parameter names be different in different versions. Maybe try changing "weather_params.cloudyness" to "weather_params.cloudiness".

**Comment by wpp201820601009** [comment]
I'm using Carla 0.9.9, yes, when I put "weather_params.cloudyness" Change to "weather_params.cloudiness"，it works. Thank you very much.
