### ISSUE TITLE
lane_change

### ISSUE THREAD

**Issue by wpp201820601009** [LucyWang01/SURF_Safe_Reconfiguration#2]
Excuse me, I have some questions about lane change, that is, in automatic mode, will vehicles change lanes by themselves? At present, I have tried many times. Under autonomous mode, vehicles do not change lanes. Only by pressing "a" or "d", can they change lanes. What I originally thought was that the destination and the road that the vehicle drives are not the same road The car will change lanes in autonomous mode, but it doesn't.

Looking forward to your reply, it will be very helpful to me, thank you

**Comment by KeyingLucyWang** [comment]
I actually haven't implemented that feature. You could add in that feature by looking into the LocalPlanner (specifically the compute_next_waypoints method).

**Comment by wpp201820601009** [comment]
Thank you very much for your reply. Sorry to see it now. Thank you again.
